name: cloudflare

services:
  cloudflared:
    image: cloudflare/cloudflared:latest
    container_name: cloudflared
    restart: unless-stopped
    command: tunnel --no-autoupdate run
    environment:
      - TUNNEL_TOKEN=TUNNEL_TOKEN_PLACEHOLDER
    networks:
      - proxy-network

networks:
  proxy-network:
    name: proxy-network
    external: true
